name: control-lora
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.34.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - bitsandbytes==0.43.3
      - blessed==1.20.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==2.21.0
      - diffusers==0.29.2
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gpustat==1.1.1
      - huggingface-hub==0.24.6
      - idna==3.8
      - imageio==2.35.1
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - packaging==24.1
      - pandas==2.0.3
      - peft==0.12.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - protobuf==5.28.0
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - safetensors==0.4.4
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.2
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.16
      - tokenizers==0.19.1
      - torch==2.4.1
      - torchmetrics==1.5.2
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.17.8
      - wcwidth==0.2.13
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.9.11
      - zipp==3.20.1
prefix: /home/wzb/miniconda3/envs/control-lora
